---
- hosts: all
  remote_user: ec2-user
  become: yes
  tasks:

  - name: copy dockerfile into Remote machine
    copy:
      src: Dockerfile
      dest: .

  - name: copy war file into Remote machine
    copy:
      src: webapp.war
      dest: .

  - name: Stop the existing container
    command: docker stop newcontainer
    ignore_errors: True

  - name: remove the stopped container
    command: docker rm newcontainer
    ignore_errors: True

  - name: remove the existing image
    command: docker rmi newimage
    ignore_errors: True

  - name: creating new image
    command: docker build -t newimage .

  - name: creating a new container
    command: docker run -itd --name newcontainer -p 4444:8080 newimage